<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9B8839P" failures="0" tests="16" name="com.qa.app.tests.LoginPageTest" time="40.551" errors="2" timestamp="2022-08-14T15:35:58 EDT" skipped="6">
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyLoginPageHeader" time="0.090"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyLoginPageHeader" time="0.064"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyRememberMeLink" time="0.076"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyRememberMeLink" time="0.086"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifySignUp" time="0.066"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifySignUp" time="0.060"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyForgotPassword" time="0.060"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="verifyForgotPassword" time="0.079"/>
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.376">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.029">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.app.pages.LoginPage.doLogin(LoginPage.java:54)
at com.qa.app.tests.LoginPageTest.doLogin(LoginPageTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="3.291">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.018">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.417">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.019">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.431">
    <skipped/>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="com.qa.app.tests.LoginPageTest" name="doLogin" time="5.389">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.app.pages.HomePage.getName(HomePage.java:16)
at com.qa.app.tests.LoginPageTest.doLogin(LoginPageTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- doLogin -->
  <system-out/>
</testsuite> <!-- com.qa.app.tests.LoginPageTest -->
